import { Component } from '@angular/core';
import { Products } from '../../models/products';
import { CommonModule } from '@angular/common';
import { ProductService } from '../services/product.service';
import { Observable } from 'rxjs';
import { AuthService } from '../services/auth.service';
import { Users } from '../../models/users';
import { ToastrService } from 'ngx-toastr';
import { CartService } from '../services/cart.service';
import { Cart } from '../../models/cart';

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './products.component.html',
  styleUrl: './products.component.css',
})
export class ProductsComponent {
  products$: Observable<Products[]>;
  users$: Users | null = null;
  constructor(
    private productService: ProductService,
    private authService: AuthService,
    private toastr: ToastrService,
    private cartService: CartService
  ) {
    authService.listenToUsers().subscribe((data: Users | null) => {
      this.users$ = data;
    });
    this.products$ = productService.getAllProducts();
  }
  async addToCart(product: Products) {
    if (this.users$ === null) {
      this.toastr.error('No user found, please login');
      return;
    }

    try {
      const cart: Cart = {
        id: '', // This will be auto-generated by Firestore
        userID: this.users$.id,
        productID: product.id,
        quantity: 1, // Starting with a quantity of 1
        createdAt: new Date(),
      };

      await this.cartService.addToCart(cart);
      this.toastr.success('Product added to cart!');
    } catch (error) {
      this.toastr.error('Failed to add product to cart');
    }
  }
}
